---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: elasticsearch
  template:
    metadata:
      labels:
        name: elasticsearch
    spec:
      containers:
      - image: elasticsearch:7.10.1
        name: elasticsearch
        ports:
        - name: elasticsearch
          containerPort: 9200
        env:
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: discovery.type
          value: single-node
        resources:
          limits:
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 1024Mi
        volumeMounts:
          - name: elasticsearch
            mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: elasticsearch
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    name: elasticsearch
  namespace: kube-system
spec:
  ports:
  - port: 9200
    targetPort: 9200
  selector:
    name: elasticsearch
